#!/usr/bin/env bash
set -euo pipefail

# Installs the lcd-2 board fork into node_modules/@geastack/targets.
#
# The Waveshare ESP32-S3-Touch-LCD-2 has no published Geastack target, so we
# forked sticks3 into a new target inside the installed package (see
# skills/bringup-waveshare-lcd2). `npm ci` deletes that fork, and the edits
# were never reconstructible from memory — so the fork's real home is now the
# committed baseline under third_party/geastack-targets, and this script is the
# only sanctioned way to materialize it into node_modules. Rebuilding "from
# scratch" by hand on a fresh clone WILL regress pins, link flags and the touch
# map. Run this after every `npm ci` or `npm update`; the script is idempotent.
#
# Two upstream files carry small patches (gea_framework.cmake here, a one-line
# IDF quote-escaping fix in the ESP-IDF tree); both are applied as patch files
# and detected when already present.

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
vendor="$root/third_party/geastack-targets"
pkg="$root/node_modules/@geastack/targets"
target=esp32-s3-waveshare-touch-lcd-2
pin=0.1.87

version="$(node -p "require('$pkg/package.json').version")"
if [ "$version" != "$pin" ]; then
  echo "install-lcd2-fork: @geastack/targets is $version, fork is cut against $pin." >&2
  echo "Restore the pinned package set with \`npm ci\` first; do not port the fork by eye." >&2
  exit 1
fi

# 1. The forked target directory, verbatim from the baseline. managed_components
#    is regenerated by the IDF component manager; never vendor it.
rsync -a --delete --exclude managed_components --exclude .DS_Store \
  "$vendor/targets/$target/" "$pkg/targets/$target/"
echo "install-lcd2-fork: target $target restored."

# 2. Register the fork in targets.json, preserving key order and adding only
#    what is missing. ipcTaskStackSize matters: the default starves the IDF IPC
#    task once the audio arenas are up.
node -e '
const fs = require("fs")
const file = process.argv[1]
const id = process.argv[2]
const data = JSON.parse(fs.readFileSync(file, "utf8"))
if (!data[id]) {
    data[id] = {
        adapter: "esp32-idf",
        targetPath: "targets/" + id,
        flashSize: "16MB",
        appPlatform: "esp32",
        idfTarget: "esp32s3",
        esptoolChip: "esp32s3",
        ipcTaskStackSize: "4096",
    }
    fs.writeFileSync(file, JSON.stringify(data, null, 2) + "\n")
    console.log("install-lcd2-fork: " + id + " registered in targets.json.")
} else {
    console.log("install-lcd2-fork: targets.json registration already present.")
}
' "$pkg/targets.json" "$target"

# 3. gea_framework.cmake: quoted GEA_EMBEDDED_CPP_BOARD + filter-list collision
#    fix. -N skips hunks that are already in place.
if patch -N -p1 --forward --dry-run -d "$pkg" \
  -i "$vendor/patches/geastack-targets-${pin}__gea_framework.cmake.patch" > /dev/null 2>&1; then
  patch -N -p1 --forward -d "$pkg" \
    -i "$vendor/patches/geastack-targets-${pin}__gea_framework.cmake.patch"
  echo "install-lcd2-fork: gea_framework.cmake patched."
else
  echo "install-lcd2-fork: gea_framework.cmake already patched (or does not apply cleanly — check by hand)."
fi

# 4. ESP-IDF fix: __build_write_properties did not escape embedded quotes, so
#    any quoted COMPILE_DEFINITIONS value (which the patch above relies on)
#    produces a syntax error in the requirements -P pass. Lives in the IDF tree
#    at ~/esp/esp-idf, survives `gea setup` re-runs.
idf="${IDF_PATH:-$HOME/esp/esp-idf}"
idfpatch="$vendor/patches/esp-idf-6.0.2__build-cmake-quoted-properties.patch"
if [ -d "$idf/.git" ]; then
  if git -C "$idf" apply --reverse --check "$idfpatch" > /dev/null 2>&1; then
    echo "install-lcd2-fork: esp-idf build.cmake already patched."
  elif git -C "$idf" apply --check "$idfpatch" > /dev/null 2>&1; then
    git -C "$idf" apply "$idfpatch"
    echo "install-lcd2-fork: esp-idf build.cmake patched at $idf."
  else
    echo "install-lcd2-fork: WARNING — esp-idf patch neither applies nor is applied at $idf; inspect tools/cmake/build.cmake." >&2
  fi
else
  echo "install-lcd2-fork: no git tree at $idf; apply patches/esp-idf-6.0.2__build-cmake-quoted-properties.patch by hand." >&2
fi

echo "install-lcd2-fork: done. Next: npm run build:firmware:lcd2"
